<?php

/**
 * @file
 * This module provides access checking of the current language of the site.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_node_access().
 */
function content_language_access_node_access(NodeInterface $node, $op, AccountInterface $account) {
  /** @var \Drupal\Core\Language\LanguageInterface $language */
  $language = \Drupal::languageManager()->getCurrentLanguage();

  // Only checks for view permission.
  if (is_object($node) && $op == 'view') {
    /** @var \Drupal\Core\Language\LanguageInterface[] $node_languages */
    $node_languages = $node->getTranslationLanguages();
    // Ignoring the language is neutral and not applicable.
    if (!isset($node_languages[\Drupal\Core\Language\Language::LANGCODE_NOT_SPECIFIED]) &&
      !isset($node_languages[\Drupal\Core\Language\Language::LANGCODE_NOT_APPLICABLE])
    ) {
      // Verifies if the current language is the same of the content.
      if (!isset($node_languages[$language->getId()])) {
        // Checks the configuration defined in admin page.
        /** @var \Drupal\Core\Config\ImmutableConfig $config */
        $config = Drupal::config('content_language_access.settings');

        foreach ($node_languages as $language_node_key => $node_language) {
          $actual_language_permission = (bool) $config->get($language->getId() . '-' . $language_node_key);
          if (!$actual_language_permission && !$account->hasPermission('bypass content_language_access')) {
            return AccessResult::forbidden();
          }
        }
      }
    }
  }

  return AccessResult::neutral();
}

/**
 * Implements hook_help().
 */
function content_language_access_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the content_language_access module.
    case 'help.page.content_language_access':
      return '<p>' . t('Content Language Access Module restricts the access of only contents with language (except neutral language) that are equal of the actual Drupal language being accessed or others that were previous configured in the <a href=":content_language_access">admin page</a>.', [':content_language_access' => \Drupal::url('content_language_access.admin_form')]) . '</p>';

    // Help for admin page for the content_language_access module.
    case 'content_language_access.admin_form':
      return '<p>' . t('This page provides an interface for configuring more languages that can be accessed from a Drupal language') . '</p>';
  }
}
