<?php

/**
 * @file
 * This module provides access checking of the current language of the site
 * with the language of the content (language neutral are not considered).
 */

/**
 * Implements hook_node_access().
 *
 * @global object $language
 */
function content_language_access_node_access($node, $op, $account) {
  global $language;

  // Only checks for view permission.
  if (is_object($node) && $op == 'view') {
    if ($node->language) {
      // Verifies if the current language is the same of the content.
      if ($node->language != $language->language) {
        return NODE_ACCESS_DENY;
      }
    }
  }

  return NODE_ACCESS_IGNORE;
}
